import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect } from 'react';
const { Configuration, OpenAIApi } = require("openai");

const inter = Inter({ subsets: ['latin'] });

export default function Home({data}) {

  // useEffect(()=> {
  //   async function fetchData() {
  //   const configuration = new Configuration({
  //     apiKey: process.env.API_KEY,
  //   });
  //   const openai = new OpenAIApi(configuration);
  //   const data = await openai.listModels();
  //   return data;
  // }
  
  // console.log(fetchData())
  // }, [])

  console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <>AI</>
      </main>
    </>
  )
}

function stringify(data) {
  let cache = [];
  let str = JSON.stringify(data, function(key, value) {
    if (typeof value === "object" && value !== null) {
      if (cache.indexOf(value) !== -1) {
        // Circular reference found, discard key
        return;
      }
      // Store value in our collection
      cache.push(value);
    }
    return value;
  });
  cache = null; // reset the cache
  return str;
}

// This gets called on every request
export async function getServerSideProps() {


  const configuration = new Configuration({
    apiKey: process.env.API_KEY,
  });
  const openai = new OpenAIApi(configuration);
  let data = await openai.listModels();
  data = stringify(data);
//   // console.log(data);
// //   // Pass data to the page via props
  return { props: JSON.parse(data) }
}
